spring.application.name=order-service
server.port=8091
spring.cloud.discovery.enabled=false
spring.cloud.config.enabled=false

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:orders-db

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/saadbr-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8090/realms/saadbr-realm/protocol/openid-connect/certs
